server:
  port: 8004
spring:
  servlet:
    multipart:
      max-file-size: 100MB
  datasource:
   url: jdbc:mysql://localhost:3306/wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT&B8
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: root
   password: 123456


file:
  upload: C:/upload
